# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import logging
from automatic_post_sender import post_sender

# for terminal log messages
logging.basicConfig(level=logging.DEBUG, format=' %(asctime)s - %(name)s - %(levelname)s - %(message)s')    


class QPlainTextEditLogger(logging.Handler):
    pass





class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(484, 423)

        # gönder butonu
        self.GONDER = QtWidgets.QPushButton(Dialog)
        self.GONDER.setGeometry(QtCore.QRect(360, 370, 111, 24)) 
        self.GONDER.setObjectName("GONDER")

        # araba fotolarını olduğu path
        self.post_path_edit = QtWidgets.QLineEdit(Dialog)
        self.post_path_edit.setGeometry(QtCore.QRect(120, 20, 341, 24))
        self.post_path_edit.setObjectName("post_path_edit")

        # fotoların olduğu path deki resimlerin hepsini göster
        self.show_future_posts = QtWidgets.QListWidget(Dialog)
        self.show_future_posts.setGeometry(QtCore.QRect(10, 150, 461, 181))
        self.show_future_posts.setObjectName("show_future_posts")

        # labellar
        self.post_path_label = QtWidgets.QLabel(Dialog)
        self.post_path_label.setGeometry(QtCore.QRect(20, 20, 58, 17))
        self.post_path_label.setObjectName("post_path_label")

        # kullanıcı adı
        self.username_edit = QtWidgets.QLineEdit(Dialog)
        self.username_edit.setGeometry(QtCore.QRect(120, 50, 241, 24))
        self.username_edit.setObjectName("username_edit")

        # şifre
        self.password_edit = QtWidgets.QLineEdit(Dialog)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_edit.setGeometry(QtCore.QRect(120, 80, 241, 24))
        self.password_edit.setObjectName("password_edit")

        # labellar
        self.password_label = QtWidgets.QLabel(Dialog)
        self.password_label.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.password_label.setObjectName("password_label")
        self.username_label = QtWidgets.QLabel(Dialog)
        self.username_label.setGeometry(QtCore.QRect(20, 50, 71, 20))
        self.username_label.setObjectName("username_label")

        # en son kullanıcı butona bastıktan sonra
        # aynı terminal ekranında olduğu gibi gönderilen postun adının yazması için
        self.image_name_and_posted = QtWidgets.QLabel(Dialog)
        self.image_name_and_posted.setGeometry(QtCore.QRect(20, 340, 481, 51))
        self.image_name_and_posted.setText("")
        self.image_name_and_posted.setObjectName("image_name_and_posted")

        self.loggin = QtWidgets.QPlainTextEdit(Dialog)
        self.loggin.setGeometry(QtCore.QRect(10, 150, 461, 201))
        self.loggin.setObjectName("loggin")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.GONDER.clicked.connect(self.onClick)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Anti Speed Bump Crew Automatic Post Sender Bot"))
        self.GONDER.setText(_translate("Dialog", "SEND POST"))
        self.post_path_label.setText(_translate("Dialog", "Post\'s path"))
        self.password_label.setText(_translate("Dialog", "password"))
        self.username_label.setText(_translate("Dialog", "username"))

    def onClick(self):
        post_sender(
            main_path=self.post_path_edit,
            username=self.username_edit,
            password=self.password_edit
        )


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
