'id':
  - '["id"]'

'username':
  - '["username"]'

'following_count':
  - '["edge_followed_by"]["count"]'

'follower_count':
  - '["edge_followed_by"]["count"]'

'mutual_follow_by':
  - '["edge_mutual_followed_by"]["count"]'
